export interface GanttTask {
  taskNum: number;
  gate: string;
  task: string;
  category: string;
  teamResponsible: string;
  people: string[];
  taskDependency: number | null;
  status: string;
  readyToBeInitiated: string;
  dependencyStatus: string;
  workDays: number;
  startDate: string;
  endDate: string;
}

export interface GanttProject {
  projectName: string;
  projectStartDate: string;
  onShelfDate: string;
  shelfLifeTestCompleteDate: string;
  tasks: GanttTask[];
}

// Men's Hair Product Gantt - full data from CSV
export const mensHairGantt: GanttProject = {
  projectName: "MEN'S HAIR",
  projectStartDate: "12/15/2025",
  onShelfDate: "8/31/2026",
  shelfLifeTestCompleteDate: "8/10/2026",
  tasks: [
    { taskNum: 1, gate: "Gate 0", task: "Product Brief", category: "Market Assessment", teamResponsible: "Product Development", people: ["John", "Dana"], taskDependency: null, status: "Completed", readyToBeInitiated: "", dependencyStatus: "", workDays: 5, startDate: "12/15/2025", endDate: "12/22/2025" },
    { taskNum: 2, gate: "Gate 0", task: "Gate 1 Approval", category: "Gate Approval", teamResponsible: "Product Development", people: ["John", "Dana"], taskDependency: 1, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "12/22/2025", endDate: "12/23/2025" },
    { taskNum: 3, gate: "Gate 1", task: "Formulation", category: "Formulation", teamResponsible: "Product Development", people: ["John", "Matt"], taskDependency: 2, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "12/23/2025", endDate: "12/24/2025" },
    { taskNum: 4, gate: "Gate 1", task: "RM Sourcing, Costing & Documentation", category: "Formulation", teamResponsible: "Product Development", people: ["John", "Matt", "Britt"], taskDependency: 3, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "12/24/2025", endDate: "12/31/2025" },
    { taskNum: 5, gate: "Gate 1", task: "Costing Analysis", category: "Formulation", teamResponsible: "Product Development", people: ["John", "Matt", "Britt"], taskDependency: 4, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "12/31/2025", endDate: "1/7/2026" },
    { taskNum: 6, gate: "Gate 1", task: "Notify Quality of Arrival of New RMs", category: "Quality Assurance", teamResponsible: "Quality", people: ["Quality"], taskDependency: 4, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "12/31/2025", endDate: "1/7/2026" },
    { taskNum: 7, gate: "Gate 1", task: "RM Sample Allocation for Prototyping", category: "Prototyping", teamResponsible: "Product Development", people: ["Matt", "Britt", "Florian/Erin P."], taskDependency: 6, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "1/7/2026", endDate: "1/8/2026" },
    { taskNum: 8, gate: "Gate 1", task: "Product Information Sheet", category: "Product Information Management", teamResponsible: "Product Development", people: ["John", "Dana"], taskDependency: 2, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 2, startDate: "12/23/2025", endDate: "12/25/2025" },
    { taskNum: 9, gate: "Gate 1", task: "Profit and Loss Statement", category: "Financial Modeling", teamResponsible: "Finance", people: ["John", "Dana", "Cheryl", "Marketing", "Brand Manager", "Digital Marketing"], taskDependency: 5, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "1/7/2026", endDate: "1/14/2026" },
    { taskNum: 10, gate: "Gate 1", task: "Preliminary SFP Creation", category: "Prototyping", teamResponsible: "Product Development", people: ["Shefali"], taskDependency: 3, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "2/3/2026", endDate: "2/4/2026" },
    { taskNum: 11, gate: "Gate 1", task: "Gate 2 Approval Document", category: "Gate Approval", teamResponsible: "Product Development", people: ["John", "Dana"], taskDependency: 10, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 2, startDate: "2/5/2026", endDate: "2/9/2026" },
    { taskNum: 12, gate: "Gate 2", task: "Prototyping", category: "Prototyping", teamResponsible: "Product Development", people: ["Matt"], taskDependency: 11, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "2/16/2026", endDate: "2/23/2026" },
    { taskNum: 13, gate: "Gate 2", task: "Directional Sensory Approval for Prototypes", category: "Prototyping", teamResponsible: "Product Development", people: ["Marketing"], taskDependency: 12, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "2/23/2026", endDate: "3/2/2026" },
    { taskNum: 14, gate: "Gate 2", task: "Qualify New Suppliers and RMs (as needed)", category: "Quality Assurance", teamResponsible: "Quality", people: ["Shefali", "Quality"], taskDependency: 11, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "2/9/2026", endDate: "2/16/2026" },
    { taskNum: 15, gate: "Gate 2", task: "SKU Creation", category: "Product Information Management", teamResponsible: "", people: ["Mckenzie"], taskDependency: 11, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "2/9/2026", endDate: "2/10/2026" },
    { taskNum: 16, gate: "Gate 2", task: "UPC Generation", category: "Product Information Management", teamResponsible: "", people: ["Dana"], taskDependency: 11, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "2/9/2026", endDate: "2/10/2026" },
    { taskNum: 17, gate: "Gate 2", task: "PSF Submittal", category: "Production Planning", teamResponsible: "Product Development", people: ["Matt", "Dana"], taskDependency: 12, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 2, startDate: "2/23/2026", endDate: "2/25/2026" },
    { taskNum: 18, gate: "Gate 2", task: "Product Setup in Netsuite", category: "Production Planning", teamResponsible: "Operations", people: ["Mckenzie"], taskDependency: 17, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 2, startDate: "2/25/2026", endDate: "2/27/2026" },
    { taskNum: 19, gate: "Gate 2", task: "GMP Pilot WO Creation and Scheduling", category: "Production Planning", teamResponsible: "Operations", people: ["Mckenzie"], taskDependency: 18, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 2, startDate: "2/27/2026", endDate: "3/3/2026" },
    { taskNum: 20, gate: "Gate 2", task: "New Product Development Checklist", category: "Label", teamResponsible: "Product Development", people: [], taskDependency: 11, status: "Not Needed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 2, startDate: "2/9/2026", endDate: "2/11/2026" },
    { taskNum: 21, gate: "Gate 2", task: "Final Product Name & PDP Claim", category: "Product Information Management", teamResponsible: "Marketing", people: ["John", "Shefali", "Marketing", "Digital Marketing"], taskDependency: 11, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 5, startDate: "2/9/2026", endDate: "2/16/2026" },
    { taskNum: 22, gate: "Gate 2", task: "Marketing Copy Creation & Approval", category: "Marketing", teamResponsible: "Marketing", people: ["John", "Shefali", "Marketing"], taskDependency: 11, status: "In Progress", readyToBeInitiated: "YES", dependencyStatus: "Completed", workDays: 30, startDate: "2/9/2026", endDate: "3/23/2026" },
    { taskNum: 23, gate: "Gate 2", task: "Label Manuscript", category: "Label", teamResponsible: "Regulatory", people: ["Shefali"], taskDependency: 12, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 3, startDate: "2/23/2026", endDate: "2/26/2026" },
    { taskNum: 24, gate: "Gate 2", task: "Label Design & Internal Approval", category: "Label", teamResponsible: "Label Team", people: ["Label Team"], taskDependency: 23, status: "In Progress", readyToBeInitiated: "YES", dependencyStatus: "Completed", workDays: 5, startDate: "2/26/2026", endDate: "3/5/2026" },
    { taskNum: 25, gate: "Gate 2", task: "GMP Pilot RM Order and Receipt", category: "Pilot", teamResponsible: "Purchasing", people: ["Britt"], taskDependency: 14, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 13, startDate: "2/16/2026", endDate: "3/5/2026" },
    { taskNum: 26, gate: "Gate 2", task: "GMP Pilot RM Testing & Release + Buffer", category: "Pilot", teamResponsible: "Quality", people: ["Quality"], taskDependency: 25, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 4, startDate: "3/5/2026", endDate: "3/11/2026" },
    { taskNum: 27, gate: "Gate 2", task: "New RM Specs", category: "Quality Assurance", teamResponsible: "", people: ["Matt", "Shefali", "Quality"], taskDependency: 26, status: "Not Initiated", readyToBeInitiated: "YES", dependencyStatus: "Completed", workDays: 2, startDate: "3/11/2026", endDate: "3/13/2026" },
    { taskNum: 28, gate: "Gate 2", task: "GMP Pilot Manufacturing - Blending", category: "Pilot", teamResponsible: "Manufacturing", people: ["Florian/Erin P."], taskDependency: 26, status: "Completed", readyToBeInitiated: "Completed", dependencyStatus: "Completed", workDays: 1, startDate: "4/7/2026", endDate: "4/8/2026" },
    { taskNum: 29, gate: "Gate 2", task: "GMP Pilot Blend Testing", category: "Pilot", teamResponsible: "", people: [], taskDependency: 28, status: "Completed", readyToBeInitiated: "NO", dependencyStatus: "", workDays: 12, startDate: "4/8/2026", endDate: "4/24/2026" },
    { taskNum: 30, gate: "Gate 2", task: "GMP Pilot Manufacturing - Encapsulation", category: "Pilot", teamResponsible: "", people: [], taskDependency: 29, status: "Completed", readyToBeInitiated: "NO", dependencyStatus: "", workDays: 1, startDate: "4/24/2026", endDate: "4/27/2026" },
    { taskNum: 31, gate: "Gate 2", task: "GMP Pilot Caps Testing", category: "Pilot", teamResponsible: "Quality", people: ["Quality"], taskDependency: 30, status: "In Progress", readyToBeInitiated: "YES", dependencyStatus: "Completed", workDays: 5, startDate: "4/27/2026", endDate: "5/4/2026" },
    { taskNum: 32, gate: "Gate 2", task: "Accelerated Testing", category: "Pilot", teamResponsible: "", people: ["Quality"], taskDependency: 31, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 70, startDate: "5/4/2026", endDate: "8/10/2026" },
    { taskNum: 33, gate: "Gate 2", task: "Consumer Sensory Analysis", category: "Pilot", teamResponsible: "", people: ["John", "Dana", "Cheryl"], taskDependency: 31, status: "Not Needed", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 0, startDate: "5/4/2026", endDate: "5/4/2026" },
    { taskNum: 34, gate: "Gate 2", task: "Label Updates and Approval (if required based on GMP Pilot)", category: "Label", teamResponsible: "Label Team", people: ["Label Team"], taskDependency: 31, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 0, startDate: "5/4/2026", endDate: "5/4/2026" },
    { taskNum: 35, gate: "Gate 2", task: "PSF Updates (if required based on GMP pilot)", category: "Production Planning", teamResponsible: "Product Development", people: ["Matt", "Mckenzie"], taskDependency: 31, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 0, startDate: "5/4/2026", endDate: "5/4/2026" },
    { taskNum: 36, gate: "Gate 2", task: "Gate 3 Approval Document", category: "Gate Approval", teamResponsible: "Product Development", people: ["John", "Dana"], taskDependency: 31, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 2, startDate: "5/4/2026", endDate: "5/6/2026" },
    { taskNum: 37, gate: "Gate 3", task: "Ask Cheryl to Add to Next LE", category: "Manufacturing/Operations", teamResponsible: "Product Development", people: ["Dana"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 1, startDate: "5/6/2026", endDate: "5/7/2026" },
    { taskNum: 38, gate: "Gate 3", task: "Notify Warehouse of Incoming Product Receipt", category: "Product Information Management", teamResponsible: "Product Development", people: ["Dana"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 1, startDate: "5/6/2026", endDate: "5/7/2026" },
    { taskNum: 39, gate: "Gate 3", task: "Sell Sheet Design", category: "Marketing", teamResponsible: "Marketing", people: ["Marketing"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 20, startDate: "5/6/2026", endDate: "6/3/2026" },
    { taskNum: 40, gate: "Gate 3", task: "Marketing Launch Materials Design", category: "Marketing", teamResponsible: "Marketing", people: ["Marketing"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 20, startDate: "5/6/2026", endDate: "6/3/2026" },
    { taskNum: 41, gate: "Gate 3", task: "Schedule Training for Customer Service and Sales", category: "Marketing", teamResponsible: "Marketing", people: ["Marketing"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 10, startDate: "5/6/2026", endDate: "5/20/2026" },
    { taskNum: 42, gate: "Gate 3", task: "E-commerce Preparation", category: "Marketing", teamResponsible: "E-commerce", people: ["Marketing", "Digital Marketing"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 15, startDate: "5/6/2026", endDate: "5/27/2026" },
    { taskNum: 43, gate: "Gate 3", task: "Distributor Onboarding", category: "Marketing", teamResponsible: "Marketing", people: ["Dana", "Marketing"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 20, startDate: "5/6/2026", endDate: "6/3/2026" },
    { taskNum: 44, gate: "Gate 3", task: "Add Pricing in Netsuite", category: "Product Information Management", teamResponsible: "Marketing", people: ["Marketing"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 2, startDate: "5/6/2026", endDate: "5/8/2026" },
    { taskNum: 45, gate: "Gate 3", task: "Product Setup in Netsuite Updates (if required based on GMP pilot)", category: "Production Planning", teamResponsible: "Operations", people: ["Mckenzie"], taskDependency: 31, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 2, startDate: "5/4/2026", endDate: "5/6/2026" },
    { taskNum: 46, gate: "Gate 3", task: "Full Scale Production WO Creation and Scheduling", category: "Production Planning", teamResponsible: "Operations", people: ["Mckenzie"], taskDependency: 31, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "In Progress", workDays: 2, startDate: "5/4/2026", endDate: "5/6/2026" },
    { taskNum: 47, gate: "Gate 3", task: "Full Scale Production RM Order and Receipt", category: "Full Scale Production", teamResponsible: "Purchasing", people: ["Britt"], taskDependency: 45, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 0, startDate: "5/6/2026", endDate: "5/6/2026" },
    { taskNum: 48, gate: "Gate 3", task: "Label Order and Receipt", category: "Pilot/Full Scale Production", teamResponsible: "Purchasing", people: ["Britt"], taskDependency: 36, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 5, startDate: "5/6/2026", endDate: "5/13/2026" },
    { taskNum: 49, gate: "Gate 3", task: "Bottle GMP Pilot Batch", category: "Pilot", teamResponsible: "Manufacturing", people: ["Florian/Erin P."], taskDependency: 48, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 1, startDate: "5/13/2026", endDate: "5/14/2026" },
    { taskNum: 50, gate: "Gate 3", task: "GMP Pilot Batch Finished Good Release", category: "Pilot", teamResponsible: "Manufacturing", people: ["Quality"], taskDependency: 49, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 7, startDate: "5/14/2026", endDate: "5/25/2026" },
    { taskNum: 51, gate: "Gate 3", task: "Notify Dana/Erin A./Dom/Kristie or Meag when rec'd bottles", category: "Product Information Management", teamResponsible: "Operations", people: [], taskDependency: 50, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 2, startDate: "5/25/2026", endDate: "5/27/2026" },
    { taskNum: 52, gate: "Gate 3", task: "GMP Pilot Batch On Shelf", category: "Pilot", teamResponsible: "Manufacturing", people: ["Florian/Erin P."], taskDependency: 50, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 5, startDate: "5/25/2026", endDate: "6/1/2026" },
    { taskNum: 53, gate: "Gate 3", task: "Full Scale Production RM Testing & Release + Buffer", category: "Full Scale Production", teamResponsible: "Manufacturing", people: ["Quality"], taskDependency: 47, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 5, startDate: "5/6/2026", endDate: "5/13/2026" },
    { taskNum: 54, gate: "Gate 3", task: "Full Scale Manufacturing - Blending", category: "Full Scale Production", teamResponsible: "Manufacturing", people: ["Florian/Erin P."], taskDependency: 32, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 1, startDate: "8/10/2026", endDate: "8/11/2026" },
    { taskNum: 55, gate: "Gate 3", task: "Full Scale Manufacturing Blend Testing", category: "Full Scale Production", teamResponsible: "Manufacturing", people: [], taskDependency: 54, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "", workDays: 5, startDate: "8/11/2026", endDate: "8/18/2026" },
    { taskNum: 56, gate: "Gate 3", task: "Full Scale Manufacturing - Encapsulation", category: "Full Scale Production", teamResponsible: "Manufacturing", people: [], taskDependency: 55, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "", workDays: 1, startDate: "8/18/2026", endDate: "8/19/2026" },
    { taskNum: 57, gate: "Gate 3", task: "Full Scale Manufacturing Caps Testing", category: "Full Scale Production", teamResponsible: "Manufacturing", people: [], taskDependency: 56, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "", workDays: 5, startDate: "8/19/2026", endDate: "8/26/2026" },
    { taskNum: 58, gate: "Gate 3", task: "Full Scale Manufacturing - Bottling", category: "Full Scale Production", teamResponsible: "Manufacturing", people: [], taskDependency: 57, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "", workDays: 1, startDate: "8/26/2026", endDate: "8/27/2026" },
    { taskNum: 59, gate: "Gate 3", task: "Full Scale Production Finished Good Release", category: "Full Scale Production", teamResponsible: "Quality", people: ["Quality"], taskDependency: 58, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 1, startDate: "8/27/2026", endDate: "8/28/2026" },
    { taskNum: 60, gate: "Gate 3", task: "Finished Good On Shelf", category: "Full Scale Production", teamResponsible: "Operations", people: ["Florian/Erin P."], taskDependency: 59, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 1, startDate: "8/28/2026", endDate: "8/31/2026" },
    { taskNum: 61, gate: "Gate 3", task: "Product Launch with GMP Pilot Batch", category: "Product Launch", teamResponsible: "Marketing", people: [], taskDependency: 52, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 5, startDate: "6/1/2026", endDate: "6/8/2026" },
    { taskNum: 62, gate: "Gate 3", task: "Product Launch with Full Scale Production", category: "Product Launch", teamResponsible: "Marketing", people: [], taskDependency: 60, status: "Not Initiated", readyToBeInitiated: "NO", dependencyStatus: "Not Initiated", workDays: 5, startDate: "8/31/2026", endDate: "9/7/2026" },
  ],
};
